CREATE TABLE ALBUM(ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, NOMBRE VARCHAR(255), FECHA_CREACION DATE);
CREATE TABLE FOTO(ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, ALBUM_ID INT,URL VARCHAR(255), DESCRIPCION VARCHAR(255), FECHA_CREACION DATE);
ALTER TABLE FOTO
    ADD FOREIGN KEY (ALBUM_ID) 
    REFERENCES ALBUM(ID);